---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/afirth/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .perl_local_lib
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - bash-completion
  - fzf
  - gettext
  - git
  - go
  - gpg
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - perl
  - pv
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bettertouchtool
  - docker
  - dropbox
  - google-chrome
  - google-cloud-sdk
  - slack
  - transmit

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

perl_script: "~/.perl_local_lib"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - perl-local-lib
